spring:
  application:
    name: MovieApi
  datasource:
    url: jdbc:postgresql://localhost:5432/moviedb
    username: moviedb
    password: moviedb123
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"